# Files
bagpath: "/home/oskar/icetrack/data/long3"
outpath: "/home/oskar/icetrack/output/long3/"
ext_file: "/home/oskar/smooth_sailing/src/smooth_sailing/cfg/calib/ext_right.yaml"

# Topics
imu_topic: "/arduino_node/imu"
gnss_topic: "/arduino_node/gnss"
lidar_topic: "/livox_lidar_node/pointcloud2"
pose_topic: "/icetrack/pose"

max_publish_rate: 20 # For fixed rate node