# Files
bagpath: "/home/oskar/icetrack/data/long3/"
outpath: "/home/oskar/icetrack/output/test/"

int_file: "/home/oskar/smooth_sailing/src/smooth_sailing/cfg/calib/int_right.yaml"
ext_file: "/home/oskar/smooth_sailing/src/smooth_sailing/cfg/calib/ext_right.yaml"

# Topics
imu_topic: "/arduino_node/imu"
gnss_topic: "/arduino_node/gnss"
lidar_topic: "/livox_lidar_node/pointcloud2"
image_topic: "/blackfly_node/image"

pose_topic: "/fixed_lag_mapper/pose"
cloud_topic: "/fixed_lag_mapper/cloud"

imu_queue_size: 2000
gnss_queue_size: 10
lidar_queue_size: 100
image_queue_size: 10

pose_queue_size: 10
cloud_queue_size: 10

max_publish_rate: 20 # For fixed rate node


### Clean up this later ###

# Frame buffer
frame_buffer/undistort_frames: true

# Surface estimator
surface_estimator/update_interval: 10
surface_estimator/window_size: 0.1
surface_estimator/voxel_size: 1.0
surface_estimator/min_inlier_count: 25
    
surface_estimator/ransac_threshold: 0.5
surface_estimator/ransac_sample_size: 10
surface_estimator/ransac_iterations: 5

# Odometry
lidar_odometry/frame_interval: 1
lidar_odometry/min_frame_size: 5000
lidar_odometry/voxel_size: 1.0
lidar_odometry/icp_threshold: 2.0
lidar_odometry/icp_min_fitness: 0.8


# Image stuff
image_generator/generate_dataset: false
image_generator/display: true
image_generator/delay: 5.0
image_generator/offset: 2.0


cloud/pub_queue_size: 10
cloud/pub_topic: "/map/raw"