# Data and experiment folders
workspace: "/home/oskar/icetrack/workspace/long3"
exp: "test"

# Calibration files
int_file: "/home/oskar/smooth_sailing/src/smooth_sailing/cfg/calib/int_right.yaml"
ext_file: "/home/oskar/smooth_sailing/src/smooth_sailing/cfg/calib/ext_right.yaml"

# Input topics
imu_topic: "/arduino_node/imu"
gnss_topic: "/arduino_node/gnss"
lidar_topic: "/livox_lidar_node/pointcloud2"
image_topic: "/blackfly_node/image"

# Output topics
pose_topic: "/fixed_lag_mapper/pose"
frame_topic: "/fixed_lag_mapper/frame"
cloud_topic: "/fixed_lag_mapper/cloud"

### Clean up this later ###
max_playback_rate: 50

# Frame buffer
frame_buffer/window_size: 10

# Surface estimation
surface_estimator/enabled: true
surface_estimator/window_size: 0.1
surface_estimator/voxel_size: 1.0
surface_estimator/min_inlier_count: 25
    
surface_estimator/ransac_threshold: 0.5
surface_estimator/ransac_sample_size: 10
surface_estimator/ransac_iterations: 5

# Odometry
lidar_odometry/enabled: true
lidar_odometry/key_frame_interval: 5
lidar_odometry/min_frame_size: 500
lidar_odometry/voxel_size: 1.0

lidar_odometry/icp_threshold: 2.0
lidar_odometry/icp_relative_fitness: 1.0e-2
lidar_odometry/icp_relative_rmse: 1.0e-3
lidar_odometry/icp_max_iter: 10

lidar_odometry/icp_min_fitness: 0.9

# Visualizer
visualizer/enabled: true

visualizer/display: false
visualizer/publish: true
visualizer/topic: "/fixed_lag_mapper/viz"

visualizer/delay: 5.0

# Point buffer
point_buffer/buffer_size: 10.0
lidar/point_interval: 5.0e-6
lidar/min_intensity: 5.0
lidar/min_dist: 20
lidar/max_dist: 100


# Cloud processor
cloud_processor/save_clouds: false
cloud_processor/grid_size: 0.5
cloud_processor/smoothing_window_size: 3
cloud_processor/deformation_window_size: 5

# Cloud manager
cloud_manager/refine_frames: true
cloud_manager/publish_frames: false
cloud_manager/publish_cloud: true

# Cloud publisher
cloud_publisher/cloud_topic: "/icetrack/raw_cloud"
cloud_publisher/frame_topic: "/icetrack/frame"