# Data and experiment folders
workspace: "/home/oskar/icetrack/workspace/long3"
exp: "test"

# Calibration files
int_file: "/home/oskar/smooth_sailing/src/smooth_sailing/cfg/calib/int_right.yaml"
ext_file: "/home/oskar/smooth_sailing/src/smooth_sailing/cfg/calib/ext_right.yaml"

# Topic definitions
imu_topic: "/arduino_node/imu"
gnss_topic: "/arduino_node/gnss"
lidar_topic: "/livox_lidar_node/pointcloud2"
image_topic: "/blackfly_node/image"

pose_topic: "/fixed_lag_mapper/pose"
raw_cloud_topic: "/fixed_lag_mapper/raw_cloud"
processed_cloud_topic: "/fixed_lag_mapper/processed_cloud"

imu_queue_size: 2000
gnss_queue_size: 10
lidar_queue_size: 100
image_queue_size: 10

pose_queue_size: 10
raw_cloud_queue_size_: 10
processed_cloud_queue_size_: 10

### Clean up this later ###

# Frame buffer
frame_buffer/undistort_frames: true
frame_buffer/voxel_size: 1 # Negative voxel size mean no down sample
frame_buffer/window_size: 10

# Surface estimator
surface_estimator/update_interval: 10
surface_estimator/window_size: 0.1
surface_estimator/voxel_size: 1.0
surface_estimator/min_inlier_count: 25
    
surface_estimator/ransac_threshold: 0.5
surface_estimator/ransac_sample_size: 10
surface_estimator/ransac_iterations: 5

# Odometry
lidar_odometry/enabled: true
lidar_odometry/frame_interval: 1
lidar_odometry/min_frame_size: 500
lidar_odometry/icp_max_iter: 20
lidar_odometry/icp_threshold: 2.0
lidar_odometry/icp_min_fitness: 0.8


# Image stuff
image_generator/enabled: false
image_generator/display: true
image_generator/topic: "/viz/image"
image_generator/delay: 5.0
image_generator/offset: 1.0


cloud/pub_queue_size: 10
cloud/pub_topic: "/map/raw"


# Point buffer
point_buffer/buffer_size: 10.0
lidar/point_interval: 5.0e-6
lidar/min_intensity: 5.0
lidar/min_dist: 20
lidar/max_dist: 100


# Cloud processor
cloud_processor/save_clouds: true
cloud_processor/grid_size: 1.0
cloud_processor/smoothing_window_size: 5
cloud_processor/deformation_window_size: 9

# Cloud manager
cloud_manager/publish_frames: false
cloud_manager/publish_processed: true