# System
bagpath: "/home/oskar/icetrack/data/optical/"
ext_file: "/home/oskar/smooth_sailing/src/smooth_sailing/cfg/calib/ext_right.yaml"
outpath: "/home/oskar/icetrack/output/optical/"

safe_delay: 0.5 # Wait this period for possible sensor lag

##### Navigation #####

# General
nav/gravity_norm: 9.831
nav/fixed_lag: 60 # Lag interval

# Prior covariance
nav/initial_bias_sigma: 0.1
nav/initial_velocity_sigma: 1
nav/initial_position_sigma: 2

# Lever arm stuff  
nav/lever_norm_threshold: 25
nav/lever_angle_threshold: 90
nav/lever_norm_sigma: 1.0e-1
nav/lever_angle_sigma: 1.0e-2
nav/lever_altitude_sigma: 1

# Ship
/nav/ship/use_ship_navigation: false

# GNSS
nav/gnss_sigma_: 1.0
nav/gnss_crs_source: "EPSG:4326"
nav/gnss_crs_target: "EPSG:6052"
nav/gnss/innovation_norm_limit: 30

# IMU
nav/imu_timeout_interval: 1.1
nav/imu_attitude_sigma: 0.1

nav/accel_noise_sigma: 1.0e-3
nav/gyro_noise_sigma: 1.0e-4
nav/accel_bias_rw_sigma: 1.0e-4
nav/gyro_bias_rw_sigma: 1.0e-5

# LIDAR
lidar/buffer_period: 2.0
lidar/point_interval: 5.0e-6
lidar/min_intensity: 1
lidar/min_dist: 15
lidar/max_dist: 150

# Surface estimation
navigation/surface_estimation/ransac_threshold: 0.5
navigation/surface_estimation/ransac_sample_size: 10
navigation/surface_estimation/ransac_iterations: 5
navigation/surface_estimation/ransac_inlier_count: 25

navigation/surface_estimation/frame_interval: 0.1

/navigation/surface_estimation/sigma_altitude: 1.0
/navigation/surface_estimation/sigma_attitude: 0.2

# Cloud manager
cloud/window_size: 60
cloud/window_interval: 60
cloud/save_cloud: true

cloud/z_lower_bound: -3
cloud/z_upper_bound: 1